import React from 'react';
import { ArrowLeft, Lightbulb, TrendingUp, ChevronRight, Download } from 'lucide-react';

export default function ImprovementSuggestions({ doc, onNavigate }) {
  if (!doc?.summary) {
    return (
      <div className="page-content" style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', minHeight: '60vh' }}>
        <div style={{ textAlign: 'center', color: 'var(--text-3)' }}>
          <Lightbulb size={48} style={{ margin: '0 auto 12px', opacity: 0.3 }} />
          <p>No document selected or no analysis available.</p>
          <button className="btn btn-primary" style={{ marginTop: 16 }} onClick={() => onNavigate('documents')}>View Documents</button>
        </div>
      </div>
    );
  }

  const suggestions = doc.summary.improvement_suggestions || [];
  const high = suggestions.filter(s => s.impact === 'high');
  const medium = suggestions.filter(s => s.impact === 'medium');
  const low = suggestions.filter(s => s.impact === 'low');

  return (
    <div className="page-content">
      <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 14, flexWrap: 'wrap', gap: 10 }}>
        <div>
          <h1 className="page-title">Improvement Suggestions</h1>
          <p className="page-subtitle">AI-powered writing quality analysis and actionable recommendations</p>
        </div>
        <button className="btn btn-secondary" style={{ display: 'flex', alignItems: 'center', gap: 5 }}><Download size={14} /> Export</button>
      </div>
      <button className="btn btn-ghost btn-sm" style={{ marginBottom: 16, display: 'flex', alignItems: 'center', gap: 6 }}
        onClick={() => onNavigate('summary-workspace', doc)}>
        <ArrowLeft size={14} /> Back to Document
      </button>

      <div className="two-col">
        <div>
          {/* Impact summary */}
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: 12, marginBottom: 20 }}>
            {[
              { label: 'High Impact', count: high.length, color: 'var(--red)', bg: 'var(--red-dim)' },
              { label: 'Medium Impact', count: medium.length, color: 'var(--amber)', bg: 'var(--amber-dim)' },
              { label: 'Low Impact', count: low.length, color: 'var(--green)', bg: 'var(--green-dim)' },
            ].map((s, i) => (
              <div className="card" key={i} style={{ padding: '14px 16px', borderLeft: `3px solid ${s.color}` }}>
                <div style={{ fontSize: '1.8rem', fontWeight: 800, color: s.color }}>{s.count}</div>
                <div style={{ fontSize: '0.78rem', color: 'var(--text-2)', marginTop: 2 }}>{s.label}</div>
              </div>
            ))}
          </div>

          {/* All suggestions */}
          {suggestions.length === 0 ? (
            <div className="card" style={{ padding: 32, textAlign: 'center', color: 'var(--text-3)' }}>
              <Lightbulb size={32} style={{ margin: '0 auto 12px', opacity: 0.3 }} />
              <p>No suggestions available. Generate a summary first.</p>
            </div>
          ) : (
            <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
              {suggestions.map((s, i) => (
                <div className="card" key={i} style={{ padding: 16, borderLeft: `3px solid ${s.impact === 'high' ? 'var(--red)' : s.impact === 'medium' ? 'var(--amber)' : 'var(--green)'}` }}>
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8 }}>
                    <div style={{ fontWeight: 700, fontSize: '0.88rem' }}>{s.category}</div>
                    <span className={`badge ${s.impact === 'high' ? 'badge-red' : s.impact === 'medium' ? 'badge-amber' : 'badge-green'}`}>
                      {s.impact?.toUpperCase()} IMPACT
                    </span>
                  </div>
                  <p style={{ fontSize: '0.85rem', color: 'var(--text-2)', lineHeight: 1.65, marginBottom: s.example ? 10 : 0 }}>{s.suggestion}</p>
                  {s.example && (
                    <div style={{
                      fontSize: '0.78rem', background: 'rgba(0,0,0,0.3)', padding: '8px 12px',
                      borderRadius: 6, borderLeft: '2px solid var(--orange)',
                      fontFamily: 'var(--font-mono)', color: 'var(--text-2)'
                    }}>{s.example}</div>
                  )}
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Sidebar */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
          <div className="card" style={{ padding: 16 }}>
            <div className="section-label">About Suggestions</div>
            <p style={{ fontSize: '0.78rem', color: 'var(--text-2)', lineHeight: 1.6 }}>
              These suggestions are generated by analyzing the document's structure, readability, tone, and completeness using AI-powered writing analysis.
            </p>
          </div>
          <div className="card" style={{ padding: '10px 0' }}>
            <div className="section-label" style={{ paddingLeft: 14 }}>Quick Actions</div>
            {[
              { icon: <TrendingUp size={14} />, title: 'View Key Insights', sub: 'Explore document data', action: () => onNavigate('key-insights', doc) },
              { icon: <Lightbulb size={14} />, title: 'Readability Analysis', sub: 'See scores in detail', action: () => onNavigate('readability', doc) },
            ].map((a, i) => (
              <button key={i} onClick={a.action} className="action-row" style={{ width: '100%', background: 'none', border: 'none', textAlign: 'left' }}>
                <div className="action-row-icon" style={{ background: 'var(--orange-dim)', color: 'var(--orange)' }}>{a.icon}</div>
                <div className="action-row-text">
                  <div className="action-row-title">{a.title}</div>
                  <div className="action-row-sub">{a.sub}</div>
                </div>
                <ChevronRight size={14} style={{ color: 'var(--text-4)' }} />
              </button>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
